### ISSUE TITLE
./ShareButtonComponent class ShareButtonComponent caused by: No provider for WindowService!

### ISSUE THREAD

**Issue by SunilProgramobil** [MurhafSousli/ng2-sharebuttons#100]
Error: DI Error
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:34589:27) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor.bundle.js:64943:16) [angular]
    at new NoProviderError (http://localhost:4200/vendor.bundle.js:65005:16) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor.bundle.js:100854:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:100893:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:100825:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:100694:21) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:390:125) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:527:59) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:65878:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:101629:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:102057:49) [angular]
    at ElementInjector.get (http://localhost:4200/vendor.bundle.js:101133:27) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:100890:24) [angular]

**Comment by MurhafSousli** [comment]
Use `forRoot()` in your root module:
```ts
imports:  [
    // ...
    ShareButtonsModule.forRoot()
]
```

**Comment by SunilProgramobil** [comment]
That works !! Thank you very much.

**Comment by MurhafSousli** [comment]
You are welcome
