### ISSUE TITLE
AOT Fails.

### ISSUE THREAD

**Issue by kodeine** [MurhafSousli/ng2-sharebuttons#9]
```
Error: Unexpected value 'ShareButtonsModule' imported by the module 'AppModule'
    at /Projects/SL/anothernode_modules/@angular/compiler/bundles/compiler.umd.js:13996:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Projects/SL/anothernode_modules/@angular/compiler/bundles/compiler.umd.js:13981:46)
    at /Projects/SL/anothernode_modules/@angular/compiler/bundles/compiler.umd.js:12801:47
    at Array.forEach (native)
    at analyzeModules (/Projects/SL/anothernode_modules/@angular/compiler/bundles/compiler.umd.js:12800:17)
    at OfflineCompiler.analyzeModules (/Projects/SL/anothernode_modules/@angular/compiler/bundles/compiler.umd.js:12826:18)
    at CodeGenerator.codegen (/Projects/SL/anothernode_modules/@angular/compiler-cli/src/codegen.js:122:47)
    at codegen (/Projects/SL/anothernode_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Projects/SL/anothernode_modules/@angular/tsc-wrapped/src/main.js:30:16)
Compilation failed
```

**Comment by MurhafSousli** [comment]
Which starter are you using?

**Comment by kodeine** [comment]
@MurhafSousli [this one](https://github.com/qdouble/angular-webpack2-starter)

**Comment by MurhafSousli** [comment]
@kodeine I haven't touched AOT yet, If you have figured out the error, let me know please
